require("configs.nvim-tree")
require("configs.lualine")
require("configs.bufferline")
require("configs.treesitter")
require("configs.alpha")
require("configs.whichkey")
require("configs.mason")
require("configs.copilot")
require("configs.cmp")
require("configs.autopairs")
require("configs.lsp")
vim.cmd('colorscheme dracula')
