require("configs.nvim-tree")
require("configs.lualine")
require("configs.bufferline")
require("configs.treesitter")
require("configs.telescope")
require("configs.alpha")
require("configs.mason")
require("configs.copilot")
vim.cmd('colorscheme dracula')
