-- Interface
require("configs.Interface.nvim-tree")
require("configs.Interface.lualine")
require("configs.Interface.bufferline")
require("configs.Interface.alpha")
require("configs.Interface.theme")
require("configs.Interface.comment")
require("configs.Interface.telescope")
require("configs.Interface.whichkey")
require("configs.Interface.floatcmd")
require("configs.Interface.colorizer")
require("configs.Interface.coderunner")
require("configs.Interface.blankline")
require("configs.Interface.notify")
require("configs.Interface.toggleterm")
require("configs.Interface.icons")
require("configs.Git.gitsigns")
require("configs.LSP.treesitter")

-- Autocomplete
require("configs.Autocomplete.copilot")
require("configs.Autocomplete.cmp")
require("configs.Autocomplete.autopairs")
require("configs.Autocomplete.autotags")

-- LSP
require("configs.LSP.mason")
require("configs.LSP.lspconfig")
require("configs.LSP.lspsaga")
require("configs.LSP.null-ls")
